# permissions for end users to view clusterrequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterrequest-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bare-metal-operator
    app.kubernetes.io/part-of: bare-metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterrequest-viewer-role
rules:
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterrequests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterrequests/status
  verbs:
  - get
