# This rule is not used by the project bare-metal-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cloudkit.openshift.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: bare-metal-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterrequest-admin-role
rules:
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterrequests
  verbs:
  - '*'
- apiGroups:
  - cloudkit.openshift.io
  resources:
  - clusterrequests/status
  verbs:
  - get
