apiVersion: cloudkit.openshift.io/v1alpha1
kind: ClusterRequest
metadata:
  labels:
    app.kubernetes.io/name: clusterrequest
    app.kubernetes.io/instance: clusterrequest-sample
    app.kubernetes.io/part-of: bare-metal-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: bare-metal-operator
  name: clusterrequest-sample
spec:
  # TODO(user): Add fields here
